obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.5, -0.275], [0.5, 0.275], [-0.5,0.275], [-0.5, -0.275]]
inflation_radius: 0.55


obstacle_layer:
  observation_sources: hokuyo_scan
  kinect_point_cloud: {sensor_frame: hokuyo_base_laser_link, topic: /hokuyo_base/scan, data_type: LaserScan, expected_update_rate: 0, observation_persistence: 0.0, marking: true, clearing: true, min_obstacle_height: 0.08, max_obstacle_height: 2.0, track_unknown_space: false}
